spring.application.name=back

# Configuração do Banco de Dados
spring.datasource.url=${DB_URL}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Configuração do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração para inicializar o banco de dados com os scripts SQL
spring.sql.init.mode=always

# Configuração para não incluir o stacktrace nas respostas de erro
spring.web.error.include-stacktrace=never

# Configuração para adiar a inicialização do datasource até que seja necessário
spring.jpa.defer-datasource-initialization=true

# Configuração do Swagger
springdoc.swagger-ui.path=/swagger-ui.html
